sudo: false
language: go
go:
  - 1.12.x
before_install:
#  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -v ./ex3/... -coverprofile=ex3.coverprofile
#  - gover
  - goveralls -coverprofile ex3.coverprofile -service travis-ci
